### ISSUE TITLE
Bug: Agent Key Mismatch

### ISSUE THREAD

**Issue by jpwalters** [schorschii/OCO-Agent#8] opened 2023-02-23 03:02 UTC
**BUG:** After the agent self registers with the server and the server tells the agent to switch keys the agent will keep sending the original agent key until the computer is rebooted or the agent service is restarted.  Even though its updated the ini file with the new key.  The server will add a "history" log message on every "agent hello" message with the following error.  "computer found but the agent key mismatch: XXXXX".  The key that's printed is the original key from the installer.

**OS:** Windows 10
**Agent Version:** 0.16.0

**Comment by schorschii** [comment] 2023-02-23 10:37
Thanks for reporting. Unfortunately, I'm unable to reproduce it. Did you use the official packages from the Github release? On which OS did this occur?

**Comment by jpwalters** [comment] 2023-02-23 16:00
Yes, I used the windows exe from here https://github.com/schorschii/OCO-Agent/releases/tag/v0.16.0.

I've installed the agent on Window 10.

I'll working reproducing it and update this ticket with the steps.

**Comment by jpwalters** [comment] 2023-02-23 21:07
Weird ... well it did happen but I'm not able to reproduce it again either.

**Comment by schorschii** [comment] 2023-02-25 17:42
OK, I'm closing it for now, but if you can reproduce it in the future, feel free to reopen this issue.

**Closed by schorschii** 2023-02-25 17:42 UTC
